CREATE USER HYPERSCALE IDENTIFIED BY HYPERSCALE;
GRANT CONNECT,RESOURCE,DBA TO HYPERSCALE;


--------------------------------------------------------
--  DDL for Sequence DOMAIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYPERSCALE"."DOMAIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
--------------------------------------------------------
--  DDL for Sequence SEGMENT_MASTER_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "HYPERSCALE"."SEGMENT_MASTER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
   
   
   --------------------------------------------------------
--  DDL for Sequence TRANSFORMATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYPERSCALE"."TRANSFORMATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
   
  
   
--------------------------------------------------------
--  DDL for Table DOMAIN
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."DOMAIN"("DOMAIN_ID" NUMBER,"DOMAIN_NAME" VARCHAR2(255 BYTE),"URL" VARCHAR2(2000 BYTE),"SEED_URL" VARCHAR2(2000 BYTE),"DIRECTORY" VARCHAR2(2000 BYTE),"CRAWL_STATUS" VARCHAR2(255 BYTE),"URL_TYPE" VARCHAR(255 BYTE));

--------------------------------------------------------
--  DDL for Table SEGMENT_HTML_PATH_PATTERN
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."SEGMENT_HTML_PATH_PATTERN"("SEGMENT_ID" NUMBER,"PATTERN_NAME" VARCHAR2(255 BYTE),"PATTERN_FORMAT" VARCHAR2(2000 BYTE));
--------------------------------------------------------
--  DDL for Table SEGMENT_MASTER
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."SEGMENT_MASTER"("DOMAIN_ID" NUMBER,"SEGMENT_ID" NUMBER,"SEGMENT_NAME" VARCHAR2(255 BYTE),"CRAWL" NUMBER(1,0),"RULE" VARCHAR2(255 BYTE),"PRIORITY" NUMBER);
--------------------------------------------------------
--  DDL for Table URL_DETAIL
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."URL_DETAIL"("SEGMENT_ID" NUMBER,"URL" VARCHAR2(2000 BYTE),"STATUS" NUMBER(1,0),"FETCH_TIME" TIMESTAMP (6),"MODIFIED_TIME" TIMESTAMP (6),"RETRIES_SINCE_FETCH" NUMBER,"RETRY_INTERVAL" NUMBER,"SCORE" NUMBER,"SIGNATURE" VARCHAR2(2000 BYTE),"METADATA" VARCHAR2(2000 BYTE));
--------------------------------------------------------
--  DDL for Table URL_HTML_LOC
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."URL_HTML_LOC" 
   (	"URL_LOC" VARCHAR2(2000 BYTE), 
	"URL" VARCHAR2(2000 BYTE)
   );
 
   --------------------------------------------------------
--  DDL for Table SEGMENT_TRANSFORMATION
	--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."SEGMENT_TRANSFORMATION" 
   (	"TRANSFORMATION_ID" NUMBER, 
	"SEGMENT_ID" NUMBER(30,0), 
	"TRANSFORMATION_PRIORITY" NUMBER
   );

   
   --------------------------------------------------------
--  DDL for Table TRANSFORMATION_MASTER
--------------------------------------------------------

  CREATE TABLE "HYPERSCALE"."TRANSFORMATION_MASTER" 
   (	"TRANSFORMATION_ID" NUMBER, 
	"TRANSFORMATION_TYPE" VARCHAR2(30 BYTE)
   );
--------------------------------------------------------
--  DDL for Index TRANSFORMATION_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYPERSCALE"."TRANSFORMATION_MASTER_PK" ON "HYPERSCALE"."TRANSFORMATION_MASTER" ("TRANSFORMATION_ID");
--------------------------------------------------------
--  DDL for Index TRANSFORMATION_MASTER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYPERSCALE"."TRANSFORMATION_MASTER_UK1" ON "HYPERSCALE"."TRANSFORMATION_MASTER" ("TRANSFORMATION_TYPE");
--------------------------------------------------------
--  Constraints for Table TRANSFORMATION_MASTER
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."TRANSFORMATION_MASTER" ADD CONSTRAINT "TRANSFORMATION_MASTER_UK1" UNIQUE ("TRANSFORMATION_TYPE") ENABLE;
  ALTER TABLE "HYPERSCALE"."TRANSFORMATION_MASTER" ADD CONSTRAINT "TRANSFORMATION_MASTER_PK" PRIMARY KEY ("TRANSFORMATION_ID") ENABLE;
  ALTER TABLE "HYPERSCALE"."TRANSFORMATION_MASTER" MODIFY ("TRANSFORMATION_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Index DOMAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYPERSCALE"."DOMAIN_PK" ON "HYPERSCALE"."DOMAIN" ("DOMAIN_ID");

--------------------------------------------------------
--  Constraints for Table DOMAIN
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."DOMAIN" MODIFY ("DOMAIN_ID" NOT NULL ENABLE);
  ALTER TABLE "HYPERSCALE"."DOMAIN" ADD CONSTRAINT "DOMAIN_PK" PRIMARY KEY ("DOMAIN_ID");
  
--------------------------------------------------------
--  Ref Constraints for Table SEGMENT_MASTER
--------------------------------------------------------

   ALTER TABLE "HYPERSCALE"."SEGMENT_MASTER" ADD CONSTRAINT "SEGMENT_MASTER_FK1" FOREIGN KEY ("DOMAIN_ID")
	  REFERENCES "HYPERSCALE"."DOMAIN" ("DOMAIN_ID") ON DELETE CASCADE ENABLE;
  
--------------------------------------------------------
--  Constraints for Table SEGMENT_HTML_PATH_PATTERN
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."SEGMENT_HTML_PATH_PATTERN" MODIFY ("PATTERN_NAME" NOT NULL ENABLE);
  ALTER TABLE "HYPERSCALE"."SEGMENT_HTML_PATH_PATTERN" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table SEGMENT_MASTER
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."SEGMENT_MASTER" ADD PRIMARY KEY ("SEGMENT_ID");
  ALTER TABLE "HYPERSCALE"."SEGMENT_MASTER" MODIFY ("SEGMENT_NAME" NOT NULL ENABLE);
  
  
  --------------------------------------------------------
--  Constraints for Table SEGMENT_TRANSFORMATION
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."SEGMENT_TRANSFORMATION" MODIFY ("TRANSFORMATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HYPERSCALE"."SEGMENT_TRANSFORMATION" MODIFY ("TRANSFORMATION_PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "HYPERSCALE"."SEGMENT_TRANSFORMATION" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Ref Constraints for Table SEGMENT_TRANSFORMATION
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."SEGMENT_TRANSFORMATION" ADD CONSTRAINT "FK_SUPPLIER" FOREIGN KEY ("SEGMENT_ID")
	  REFERENCES "HYPERSCALE"."SEGMENT_MASTER" ("SEGMENT_ID") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table SEGMENT_HTML_PATH_PATTERN
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."SEGMENT_HTML_PATH_PATTERN" ADD CONSTRAINT "SEGMENT_HTML_PATH_PATTERN_FK1" FOREIGN KEY ("SEGMENT_ID")
	  REFERENCES "HYPERSCALE"."SEGMENT_MASTER" ("SEGMENT_ID") ON DELETE CASCADE ENABLE;
	  
--------------------------------------------------------
--  Add columns in Table SEGMENT_HTML_PATH_PATTERN
--------------------------------------------------------
 
 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN ADD FILE_NAME	VARCHAR2(200 BYTE);
 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN ADD FILE_EXT	VARCHAR2(200 BYTE);
 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN ADD FILE_TYPE	VARCHAR2(20 BYTE);
 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN ADD IS_DEFAULT	NUMBER(1,0);
 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN ADD PATTERN_ID	NUMBER;

--------------------------------------------------------
--  Drop column in Table DOMAIN
--------------------------------------------------------

 ALTER TABLE HYPERSCALE.SEGMENT_HTML_PATH_PATTERN DROP COLUMN PATTERN_NAME;
 
--------------------------------------------------------
--  Ref Constraints for Table URL_DETAIL
--------------------------------------------------------

  ALTER TABLE "HYPERSCALE"."URL_DETAIL" ADD CONSTRAINT "URL_DETAIL_SEGMENT_MASTER_FK1" FOREIGN KEY ("SEGMENT_ID")
	  REFERENCES "HYPERSCALE"."SEGMENT_MASTER" ("SEGMENT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table URL_HTML_LOC
--------------------------------------------------------

 -- ALTER TABLE "CREST"."URL_HTML_LOC" ADD CONSTRAINT "URL_HTML_LOC_URL_DETAIL_FK1" FOREIGN KEY ("URL")
--	  REFERENCES "CREST"."URL_DETAIL" ("URL") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Add column to Table URL_DETAIL
--------------------------------------------------------

 ALTER TABLE "HYPERSCALE"."URL_DETAIL" ADD LAST_FETCH_TIME TIMESTAMP;
 
 --------------------------------------------------------
--  Rename column in Table URL_DETAIL
--------------------------------------------------------

 ALTER TABLE "HYPERSCALE"."URL_DETAIL" RENAME COLUMN FETCH_TIME TO LATEST_FETCH_TIME;
 
--------------------------------------------------------
--  Add columns in Table SEGMENT_MASTER
--------------------------------------------------------
 
 ALTER TABLE "HYPERSCALE".SEGMENT_MASTER ADD NEXT_FETCH_TIME TIMESTAMP;
 ALTER TABLE "HYPERSCALE".SEGMENT_MASTER ADD CRAWl_INTERVAL NUMBER;
 ALTER TABLE "HYPERSCALE".SEGMENT_MASTER ADD URL_TYPE VARCHAR2(255);
 
 --------------------------------------------------------
--  Drop column in Table DOMAIN
--------------------------------------------------------

 ALTER TABLE "HYPERSCALE"."DOMAIN" DROP COLUMN URL_TYPE;
 
 ALTER TABLE HYPERSCALE.URL_HTML_LOC ADD PATTERN_ID NUMBER;
 ALTER TABLE HYPERSCALE.URL_HTML_LOC ADD SEGMENT_ID NUMBER;
 ALTER TABLE HYPERSCALE.URL_HTML_LOC ADD DEFAULT_LOCATION NUMBER;
 
 commit;
 
  
 --------------------------------------------------------
--  Modify,Add column in Table DOMAIN
--------------------------------------------------------
ALTER TABLE "HYPERSCALE"."DOMAIN" ADD (RAW_CONTENT_DIRECTORY VARCHAR2(200));
ALTER TABLE "HYPERSCALE"."DOMAIN" RENAME COLUMN DIRECTORY TO FINAL_CONTENT_DIRECTORY;
COMMIT;
 

--------------------------------------------------------
-- MODIFY COLUMN  IN Table SEGMENT_MASTER
--------------------------------------------------------
ALTER TABLE "HYPERSCALE"."SEGMENT_MASTER" RENAME COLUMN RULE TO URL_PATTERN_RULE;
COMMIT;

 --------------------------------------------------------
--  DDL for Sequence CRAWL_MASTER_SEQ
--------------------------------------------------------  

   CREATE SEQUENCE  "HYPERSCALE"."CRAWL_MASTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
   
   
 --------------------------------------------------------
--  DDL for Table CRAWL_MASTER
-------------------------------------------------------- 
   
   CREATE TABLE "HYPERSCALE"."CRAWL_MASTER"("CRAWL_ID" NUMBER,"LIVE" NUMBER(1,0),"PROGRESS" NUMBER(1,0),"CRAWL_START" TIMESTAMP (6),"CRAWL_COMPLETED" TIMESTAMP (6));
   
   COMMIT;
 --------------------------------------------------------
--  MODIFY COLUMN IN URL_DETAIL,URL_HTML_LOC
-------------------------------------------------------- 

ALTER TABLE "HYPERSCALE"."URL_DETAIL" ADD ("CRAWL_ID" NUMBER);
ALTER TABLE "HYPERSCALE"."CRAWL_MASTER" ADD CONSTRAINT "CRAWL_MASTER_PK" PRIMARY KEY ("CRAWL_ID"); 

--ALTER TABLE "CREST"."URL_DETAIL" DROP PRIMARY_KEY;
ALTER TABLE "HYPERSCALE"."URL_DETAIL" ADD PRIMARY KEY ("URL","CRAWL_ID");
ALTER TABLE "HYPERSCALE"."URL_HTML_LOC" ADD ("CRAWL_ID" NUMBER);
ALTER TABLE "HYPERSCALE"."URL_HTML_LOC" ADD CONSTRAINT URL_HTML_LOC_URL_DETAIL_FK1
  FOREIGN KEY ("URL", "CRAWL_ID") REFERENCES "HYPERSCALE"."URL_DETAIL" ("URL","CRAWL_ID");

	  
COMMIT;

-----------------------------------------------------------------------------------
---- USER ROLE TABLE
-----------------------------------------------------------------------------------

CREATE TABLE "HYPERSCALE"."NUTCH_USER"
  (
    "USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(150 BYTE) NOT NULL ENABLE,
    "ROLE_ID"  NUMBER(1,0) NOT NULL ENABLE,
	PRIMARY KEY ("USERNAME")
  );
Insert into HYPERSCALE.NUTCH_USER (USERNAME,PASSWORD,ROLE_ID) values ('admin','jvMPnaqAnsIbKO+Au0fFNoKtP1NjcmTlDBXSVVUi7qk=',1);

CREATE TABLE "HYPERSCALE"."ROLE_MASTER"
  (
    "ROLE_ID"   NUMBER(1,0) NOT NULL ENABLE,
    "ROLE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROLE_MASTER_PK" PRIMARY KEY ("ROLE_ID")
  );
INSERT INTO HYPERSCALE.ROLE_MASTER (ROLE_ID,ROLE_NAME) values (1,'admin');
INSERT INTO HYPERSCALE.ROLE_MASTER (ROLE_ID,ROLE_NAME) values (2,'manager');
INSERT INTO HYPERSCALE.ROLE_MASTER (ROLE_ID,ROLE_NAME) values (3,'user');

CREATE TABLE "HYPERSCALE"."SEGMENT_STATUS_MASTER"
  (
    "EVENT"  VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "STATUS" NUMBER(1,0) NOT NULL ENABLE
  );
INSERT INTO HYPERSCALE.SEGMENT_STATUS_MASTER (EVENT,STATUS) values ('SEG_RULE_CHANGED',0);
INSERT INTO HYPERSCALE.SEGMENT_STATUS_MASTER (EVENT,STATUS) values ('SEG_HTML_PATH_CHANGED',0);

ALTER TABLE HYPERSCALE.URL_HTML_LOC ADD LAST_FETCH_TIME VARCHAR2(30);
ALTER TABLE HYPERSCALE.URL_HTML_LOC ADD HTML_FILE_STATUS NUMBER(1,0) DEFAULT 0;

ALTER TABLE HYPERSCALE.TRANSFORMATION_MASTER MODIFY  TRANSFORMATION_TYPE varchar(40 BYTE);

INSERT INTO HYPERSCALE.TRANSFORMATION_MASTER (TRANSFORMATION_ID,TRANSFORMATION_TYPE) values(1,'excludeDomainURL');
INSERT INTO HYPERSCALE.TRANSFORMATION_MASTER (TRANSFORMATION_ID,TRANSFORMATION_TYPE) values(2,'excludeRequestParameters');
INSERT INTO HYPERSCALE.TRANSFORMATION_MASTER (TRANSFORMATION_ID,TRANSFORMATION_TYPE) values(3,'removeSpecialChars');
INSERT INTO HYPERSCALE.TRANSFORMATION_MASTER (TRANSFORMATION_ID,TRANSFORMATION_TYPE) values(4,'addHTMLizedComment');
INSERT INTO HYPERSCALE.TRANSFORMATION_MASTER (TRANSFORMATION_ID,TRANSFORMATION_TYPE) values(5,'removeWhiteSpace');


ALTER TABLE HYPERSCALE.CRAWL_MASTER ADD (CRAWL_STATUS VARCHAR2(255));
ALTER TABLE HYPERSCALE.CRAWL_MASTER ADD (DOMAIN_ID NUMBER NOT NULL);
--------------------------------------------------------------------------
 --CHANGES TO STATUS TRACKING---------- 
-----------------------------------------------------------------------------
CREATE SEQUENCE  "HYPERSCALE"."STATUS_TRACKER_SEQ"  START WITH 1000 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE TABLE HYPERSCALE.STATUS_TRACKER (TRACKER_ID NUMBER(20),CRAWL_ID NUMBER(6),HTMLIZE_REFRESH_STATUS VARCHAR2(255),CONSTRAINT STATUS_TRACKER_PK PRIMARY KEY (TRACKER_ID));


---------------------------------------------------------------------------------
---------Request Processing changes----------------
---------------------------------------------------------------------------------
CREATE SEQUENCE  "HYPERSCALE"."REQUEST_PROCESSOR_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
CREATE TABLE "HYPERSCALE"."REQUEST_PROCESSOR" (REQUEST_ID NUMBER,DOMAIN_ID NUMBER,EVENT VARCHAR2(40),CHECKED_SEGMENTS VARCHAR2(255), URL VARCHAR2(255),SEGMENT_ID VARCHAR2(40), IS_API NUMBER(1,0),CHECKED_URLS VARCHAR2(255),
TRACK_ID NUMBER,IS_ALL VARCHAR2(50),IS_RECURSIVE VARCHAR2(50),STATUS VARCHAR2(255),CONSTRAINT REQUEST_PROCESSOR_PK PRIMARY KEY (REQUEST_ID));

CREATE TABLE "HYPERSCALE"."REQUEST_PROCESSOR_PARAMS" (REQUEST_ID NUMBER,CHECKED_URLS VARCHAR2(255),CONSTRAINT REQUEST_PROCESSOR_FK FOREIGN KEY (REQUEST_ID) REFERENCES HYPERSCALE.REQUEST_PROCESSOR(REQUEST_ID));
---------------------------------------------------------------------------
--------Monitoring Changes------------------
------------------------------------------------------------------------------
   
CREATE SEQUENCE  "HYPERSCALE"."MONITOR_FOLDER_PATHS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;
CREATE SEQUENCE  "HYPERSCALE"."MONITOR_ACTIONS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

 CREATE TABLE "HYPERSCALE"."MONITOR_FOLDER"
  (
    "MONITOR_ID"  NUMBER NOT NULL ENABLE,
    "MONITOR_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
 "PRIORITY" NUMBER,
 CONSTRAINT "MONITOR_DATA_PK" PRIMARY KEY ("MONITOR_ID")
  );
 -----------------------------------
----MASTER DATA-------------
------------------------------------ 
INSERT INTO "HYPERSCALE"."MONITOR_FOLDER" (MONITOR_ID,MONITOR_TYPE,PRIORITY) VALUES (1,'CDN',1);
INSERT INTO "HYPERSCALE"."MONITOR_FOLDER" (MONITOR_ID,MONITOR_TYPE,PRIORITY) VALUES (2,'SPECIFIC FILE',2);
INSERT INTO "HYPERSCALE"."MONITOR_FOLDER" (MONITOR_ID,MONITOR_TYPE,PRIORITY) VALUES (3,'JSP',3);
  
  CREATE TABLE "HYPERSCALE"."MONITOR_FOLDER_PATHS"
  ("MONITOR_FOLDER_ID"  NUMBER NOT NULL ENABLE,"FOLDER_PATH" VARCHAR2(255 BYTE) NOT NULL ENABLE,
  "REGEX" VARCHAR2(50 BYTE),"MONITOR_ID" NUMBER NOT NULL,
  CONSTRAINT "MONITOR_FOLDER_PK" PRIMARY KEY ("MONITOR_FOLDER_ID"),
  CONSTRAINT "MONITOR_FOLDER_FK" FOREIGN KEY ("MONITOR_ID") REFERENCES HYPERSCALE.MONITOR_FOLDER(MONITOR_ID)
  );
  
  CREATE TABLE "HYPERSCALE"."MONITOR_FOLDER_PATH_ACTIONS"
  ("MONITOR_ACTION_ID"  NUMBER NOT NULL ENABLE,"SEGMENT" VARCHAR2(50 BYTE),
  "URL" VARCHAR2(50 BYTE),"MONITOR_FOLDER_ID"  NUMBER NOT NULL,
  CONSTRAINT "MONITOR_ACTION_PK" PRIMARY KEY ("MONITOR_ACTION_ID"),CONSTRAINT "MONITOR_ACTION_FK" FOREIGN KEY ("MONITOR_FOLDER_ID") REFERENCES HYPERSCALE.MONITOR_FOLDER_PATHS(MONITOR_FOLDER_ID)
  );
  
  CREATE TABLE "HYPERSCALE"."PURGE_MASTER"
  ("URL" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	"PURGE_RESPONSE_CODE"  NUMBER,
	"START_TIME"  VARCHAR2(30),
	"END_TIME" VARCHAR2(30)
	);
   
   CREATE TABLE "HYPERSCALE"."MONITOR_MASTER"
  ("ID"  NUMBER NOT NULL ENABLE,"TYPE" VARCHAR2(100),"VALUE" VARCHAR2(255));
  
INSERT INTO "HYPERSCALE"."MONITOR_MASTER" (ID,TYPE,VALUE) VALUES (1,'DOC_ROOT','E:\Plantronics\Development\SETUP\Apache2.2\htdocs');
---------------------------------------------------------------
---------- REGEX COLUMN SIZE INCRESED
---------------------------------------------------------------
ALTER TABLE "HYPERSCALE"."MONITOR_FOLDER_PATHS" MODIFY REGEX VARCHAR2(255);

--------------------------------------------------------------------
-------- TIME STAMPS COLUMNS ADDED TO REQUEST_PROCESSOR TABLE
--------------------------------------------------------------------
ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" ADD REQUEST_STARTED VARCHAR2(100);
ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" ADD REQUEST_COMPLETED VARCHAR2(100);

ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" MODIFY STATUS VARCHAR2(255);

ALTER TABLE "HYPERSCALE"."SEGMENT_MASTER" ADD PURGE_URL VARCHAR2(255);

ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" ADD SITEKEY VARCHAR2(50);

ALTER TABLE "HYPERSCALE"."URL_DETAIL" ADD DOMAIN_ID NUMBER;

ALTER TABLE "HYPERSCALE"."URL_HTML_LOC" ADD DOMAIN_ID NUMBER;

ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" ADD DOMAIN_LIST VARCHAR2(255);

ALTER TABLE "HYPERSCALE"."SEGMENT_STATUS_MASTER" ADD DOMAIN_ID NUMBER;

ALTER TABLE "HYPERSCALE"."DOMAIN" ADD SEG_RULE_CHANGED NUMBER(1,0) DEFAULT 0;

ALTER TABLE "HYPERSCALE"."DOMAIN" ADD SEG_HTML_PATH_CHANGED NUMBER(1,0) DEFAULT 0;

ALTER TABLE "HYPERSCALE"."REQUEST_PROCESSOR" ADD TAG VARCHAR2(255);

COMMIT;